### ISSUE TITLE
Why Next files are in "src" folder?

### ISSUE THREAD

**Issue by vincentducorps** [omarkhatibco/adonis-nextjs#1]
Hey!

There is any reason for this?
Why not keep the "resources" folder?

**Comment by omarkhatibgg** [comment]
Hi @vincentducorps 

"resources" folder also used by Email Template in Adonis.

which I thought it would be better if I separate Adonis folders from Nextjs Folder.

**Comment by vincentducorps** [comment]
Thanks for the answer.

What do you think of naming the "next" folder instead of "src"?
"src" is too generic I think ...

**Comment by omarkhatibgg** [comment]
I don't 'next' is a good name for frontEnd.

maybe I will try to find a way specify folder name as options or parameter.

**Comment by vincentducorps** [comment]
It means what it means: "next" folder for "next" files. ;)
