### ISSUE TITLE
How can I prevent constant rebuilds when running the adonis server with nodemon

### ISSUE THREAD

**Issue by CodingDive** [omarkhatibco/adonis-nextjs#2]
Hey, thank you for the provider. It is my first time using Next.js and after seeing the addon I thought I no longer have an excuse to not use it for some performance critical routes. 
When I run nodemon --inspect server.js, it goes into a loop of rebuilding the project every few seconds. How can I prevent this behavior?

**Comment by omarkhatibgg** [comment]
Hi @ReasonableDeveloper 

I'm not sure that I understand you question

I think you mean rebuilding of nextjs ?

**Comment by CodingDive** [comment]
Yes. I just want to start my adonis server and serve the next.js app along of my regular adonis routes but it keeps rebuilding the next project. It always serves the server for a few seconds, rebuilds and starts over.

**Comment by omarkhatibco** [comment]
Npm run build 
Then npm run start
The idea in next is the environment varia

**Comment by omarkhatibgg** [comment]
I think you mean running your nextjs application in production mode 
for that 

you only need to build your application first `npm run build`

then `npm run start`

**Comment by CodingDive** [comment]
No, I wanted to run nodemon because I thought it is the only way to enable hot reloading. Turns out it works by just running `node server.js`🚀
