### ISSUE TITLE
Prevent rebuild while testing

### ISSUE THREAD

**Issue by CodingDive** [omarkhatibco/adonis-nextjs#4]
I serve some Next.js routes in a larger adonis app. When I run my REST tests that contain the Client trait, Next.js rebuilds at the very beginning. This results in my tests running longer. Is there a way to prevent the rebuilds since those tests are not targeting any next.js related logic/pages?

**Comment by omarkhatibgg** [comment]
Can you share an example ?

**Comment by CodingDive** [comment]
Say I have a route serving the landing page
```JavaScript
Route.get('/', ({ request, response }) => {
  const query = request.get();
  return Next.render(request.request, response.response, '/', query);
});
```
At the very beginning, when I run my tests, the next.js project gets compiled which takes up to 3 seconds and prints following output: `Compiled successfully in 1199ms`

My .babelrc file looks like this
```JSON
{
  "presets": ["next/babel"],
  "plugins": [
    "preval",
    [
      "styled-components",
      {
        "ssr": true,
        "displayName": true,
        "preprocess": false
      }
    ]
  ]
}
```

**Comment by omarkhatibgg** [comment]
The only way to prevent nextjs from rendering is `next build` and then run your test in `production` mode

**Comment by CodingDive** [comment]
Is the rebuild caused by having the provider in my `app.js` file or by the routes? In the latter case I should be able to not serve the routes when I run the app in a test environment and prevent the compilation.

**Comment by omarkhatibgg** [comment]
It's because you have the provider in your `app.js` 
the only way you can do it now by removing the provider

**Comment by CodingDive** [comment]
Awesome. For those running into the same problem:
Since everything is JavaScript we can optionally load the provider using the spread operator on an array literal inside our `start/app.js`.
``` JavaScript
// can't `const Env = use ('Env')` here since the app.js has not loaded the use functionality.
const env = process.env.NODE_ENV;
const isTestEnvironment = env === 'testing';

const providers = [
  '@adonisjs/framework/providers/AppProvider',
  '@adonisjs/lucid/providers/LucidProvider',
  ...(!isTestEnvironment ? ['adonis-nextjs/providers/NextProvider'] : [])
];
```

You also need to put all your `next.js` routes into an extra route file and then optionally require them.
Inside your `start/routes.js` file
```JavaScript
if (!isTestEnvironment){
  require('../next/next_routes');
}
```

**Comment by omarkhatibgg** [comment]
Great you fixed it !
