### ISSUE TITLE
Prevent rebuild when running adonis CLI operations

### ISSUE THREAD

**Issue by CodingDive** [omarkhatibco/adonis-nextjs#6]
I'm sorry for opening the third issue about rebuilds. If I run a CLI command like `adonis route:list`, I'm getting rebuilds and the output of the adonis command is gone because the console seems to refresh after next has finished the compilation.
Is there anything we can do inside the provider to prevent this or is there a better way than to comment out my `next_routes.js` and the provider inside the `app.js` file?

**Comment by CodingDive** [comment]
I think this might be fixed by merging https://github.com/omarkhatibco/adonis-nextjs/pull/5/files

**Comment by omarkhatibgg** [comment]
Hi @ReasonableDeveloper 
v3.1.1 contain the fix.
