### ISSUE TITLE
constant rebuilds when using 'adonis serve --dev'

### ISSUE THREAD

**Issue by samueljoos** [omarkhatibco/adonis-nextjs#7]
Hi,
First of all great work on this package. Although it was a little complicated to get started.
The reason: Constant rebuilding  when using adonis serve --dev.
The cause: Adonis serve --dev uses nodemon and ignores following patterns by default:
```js
[ 
'/tmp/*', 
'/resources/*',
 '/public/*'
]
```
It doesn't ignore the next/* pattern

Workarounds:
1. running **adonis serve --dev -i 'next/*'** 
2. changing NEXT_FOLDER to 'resources/next'
3. run **npm run dev** but then the adonis code isn't going to reload when making changes.

Possible solution might be to put this in the documentation or moving the default next folder to something like /resources/next.

**Comment by omarkhatibgg** [comment]
Hi @samueljoos 
It's not a good idea to put next in subfolder `resources/next`, it's something related I think to nextjs

possible solution I did used before is putting next in `/resources/`

**Comment by samueljoos** [comment]
Hi @omarkhatibco 

Seems messy to put the next.js files straight into the resources folder. This would conflict much easier with the adonis resources structure. Let's say that a developer puts react components in a 'resources/views' folder which is actually reserved for the adonis edge templates. 

I am currently working with the 'resources/next' solution and I didn't notice any downsides to it for now. Can you maybe elaborate on this? Why is it actually a bad idea?

I think the ideal solution would be to keep the next.js files in the 'next' folder and have a way to configure the adonis-cli with something like an .adonisrc where we can add the ignore rule for that folder. But I don't think it's possible at this moment.

**Comment by omarkhatibgg** [comment]
Hi @samueljoos 

Seems Adonis cli has a new argument to ignore a folder.

try this.

```bash
adonis serve --dev --ignore=next/*

```
