### ISSUE TITLE
Next extends controller

### ISSUE THREAD

**Issue by TheJltres** [omarkhatibco/adonis-nextjs#9]
It would be very cool if the next object were passed to the controller.
An example is worth a thousand words:

Instead of...
```javascript
const Next = use('Adonis/Addons/Next');

Route.get('/b', ({ request, response }) => {
  const query = request.get();
  return Next.render(request.request, response.response, '/b', query);
});
```

This
```javascript
Route.get('/b', ({ request, response, next }) => {
  const query = request.get();
  return next.render(request.request, response.response, '/b', query);
});
```

I will try to do it by my self and send you a pull request, but I have never done this before.

**Comment by omarkhatibgg** [comment]
Hi @TheJltres  

Thanks for your feedback. I just want to understand what is the purpose of using it this way ? 
I mean usually you declare all routes in one file so defining next  in the old way it's not that bad.

**Comment by TheJltres** [comment]
Default view render with Adonis is sent to every method of the controller (https://adonisjs.com/docs/4.1/views)
```javascript
Route.get('hello-world', ({ view }) => {
  return view.render('hello-world')
})
```

I don't know why they do it like this, I only thought to make the "default" way.

I'm will try to send data to view like Adonis views does (https://adonisjs.com/docs/4.1/views#_loggedin), but I don't promise anything 😛

**Comment by omarkhatibgg** [comment]
@TheJltres 

Thanks I will merge your PR.

Sending data to next is not going to work, because sometimes it's just client side rendered so no data will be from the server.

also Next team in some issues encourage people to make `next` independent and make the data comes through data fetching only.

**Comment by TheJltres** [comment]
I will keep it in mind.
I will try, if it works I will create a issue and a PR, if not no problem.

Thanks for the advice!

**Comment by omarkhatibgg** [comment]
@TheJltres  

So your PR did not works as expected 

in Next routers sometime  you have to make a catch router `*` this router is using `Next.getRequestHandler()` 

```js

Route.get("*", ({ request, response, next }) => {
   const handler = next.getRequestHandler();
  return new Promise((resolve, reject) => {
    handler(request.request, response.response, (promise) => {
      promise.then(resolve).catch(reject);
    });
  });
});

```

in your case  we call this function every time we call this function, this would be consider a bad behaviour since we can defined it one  and use it many time as it state in Next examples.

```js
const Next = use("Adonis/Addons/Next");
const handler = Next.getRequestHandler();


Route.get("*", ({ request, response, next }) => {

  return new Promise((resolve, reject) => {
    handler(request.request, response.response, (promise) => {
      promise.then(resolve).catch(reject);
    });
  });
});
```

**Comment by TheJltres** [comment]
I saw it but I thought it always does...
Is this for creating multiple times the object?
Any way this is Next problem, i will try to do some research and figure out how.

If I am using multiple Adonis Controllers, I need one Next object on each of them, does that do the same?

**Comment by omarkhatibgg** [comment]
@TheJltres  usually next should be available in Adonis Controller, the main reason for this plugin was to make adonis and next to run on the same port, and use adonis as custom server for routing only. 

Next is not being able to live inside or be used in Adonis Controller, it's not something like pug,jade or edge.

**Comment by TheJltres** [comment]
But if I use a Route resource (https://adonisjs.com/docs/4.1/routing#_route_resources) I will not be able to use multiple resources.

I know it is not something like edge, my idea was send Adonis functions or objects used in the controller to the view.
If I separate Adonis and Next I can ask Adonis for those objects.

The main problem here is that Next needs to handle an "error" every time you create a Next object.

**Comment by omarkhatibgg** [comment]
@TheJltres  thats why i encourage you to use adonis as API only and Next as React app only and do not try to mix them.
